Improve feedback for volume commands
jcsteh/osara pull request #315
Opened 2020-09-28 21:25 UTC by RDMurray

Say track the first time  a track volume command is used to avoid confusion with item and take volume.
Implement feedback when changing item and take volume.

I would appreciate it if you could merge this before the new keymap, as the volume keys have changed and it will make getting used to the new keys easier.

@jcsteh  I changed lastCommand to int to allow it to be used in post commands.  I think the wrest of the Command struct is unused anyway. Is that correct or do you have something in mind for the future that requires lastCommand to be Command*?

2020-09-30 21:38 UTC, RDMurray commented
Added feedback for set item end to source media end. I hope you don't mind this being in the same pr, It is also required to avoid mistakes with the new keymap.

2020-10-01 06:42 UTC, jcsteh commented
> Added feedback for set item end to source media end. I hope you don't mind this being in the same pr, It is also required to avoid mistakes with the new keymap.

I'd prefer this be in a separate PR in future, since it's unrelated to the rest of it (except for the key map thing), but I'm not going to quibble on that for this PR.

2020-10-01 06:44 UTC, jcsteh commented
> I changed lastCommand to int to allow it to be used in post commands. I think the wrest of the Command struct is unused anyway. Is that correct or do you have something in mind for the future that requires lastCommand to be Command*?

One reason we might want to keep it as `Command*` is that custom actions don't have predefined ids; we get those at runtime. That would make matching against them difficult. That said, I can't think of a reason we'd actually do that, so I'm okay with this for now.

2020-10-01 08:03 UTC, jcsteh requested changes
Thanks!

2020-10-01 08:03 UTC, jcsteh commented on src/reaper_osara.cpp
> +	if(item == nullptr)
```suggestion
	if (!item)
```

2020-10-01 08:03 UTC, jcsteh commented on src/reaper_osara.cpp
> +	if(item == nullptr)
```suggestion
	if (!item)
```

2020-10-01 08:03 UTC, jcsteh commented on src/reaper_osara.cpp
> +	if(item == nullptr)
```suggestion
	if (!item)
```

2020-10-01 08:03 UTC, jcsteh commented on src/reaper_osara.cpp
> +	if (item == nullptr) {
```suggestion
	if (!item) {
```

2020-10-01 13:42 UTC, RDMurray commented on src/reaper_osara.cpp
> +		return nullptr;
Yes, this is a problem with a lot of commands.  I can't think of a good solution.  It is the same for track volume for example.

2020-10-02 02:36 UTC, jcsteh approved these changes

2020-10-02 02:36 UTC, jcsteh commented on src/reaper_osara.cpp
> +
Extraneous blank line.
```suggestion
```

2020-10-02 02:36 UTC, jcsteh commented on src/reaper_osara.cpp
> +	MediaItem_Take* take = GetActiveTake(item);
An empty item will have no take, so we have to check for that lest we crash.
```suggestion
	MediaItem_Take* take = GetActiveTake(item);
	if (!take) {
		return;
	}
```

2020-10-02 02:40 UTC, merged