Action feedback for "View: Set horizontal zoom to default project set…
jcsteh/osara pull request #540
Opened 2021-06-14 17:31 UTC by ScottChesworth

…ting" (ID 41190)

2021-06-14 17:33 UTC, ScottChesworth commented
@jcsteh, I feel like my branch names are getting longer and longer lol. What would you have called this?

2021-06-15 11:42 UTC, jcsteh requested changes
Thanks. Please update the readme as well.

2021-06-15 11:44 UTC, jcsteh commented
Honestly, the branch name isn't super important when you're submitting it as a PR. I'm pretty lazy with them and tend to make it as short as possible without being too cryptic. I might have called this hZoomDefault or similar.

The commit message is another matter entirely. That should be as descriptive as necessary, as you have done here.

2021-06-15 11:53 UTC, ScottChesworth commented
Oopsy, done now.

2021-06-15 11:54 UTC, jcsteh commented on readme.md
> +- Set horizontal zoom to default project setting
All of these were missing the "View: " part of the action name, so I'm adding it to all of them here.
```suggestion
- View: Zoom out horizontal: - or NumPad-
- View: Zoom in horizontal: = or NumPad+
- View: Set horizontal zoom to default project setting
```

2021-06-15 11:56 UTC, jcsteh approved these changes

2021-06-15 11:57 UTC, merged