Add action to mute the next message from OSARA
jcsteh/osara pull request #601
Opened 2021-11-15 14:02 UTC by RDMurray

For use in custom actions.  Suppresses OSARA output for the next command handled by OSARA.  See comments in issue #600.

2021-11-15 15:09 UTC, Lo-lo78 commented
Hi RDMurray, yes, it's very good, great! I've tried it with both custom 
actions and cycle actions. It always works! 👍

2021-11-15 15:13 UTC, Lo-lo78 commented
Yes, it works very well!

👍

2021-11-15 16:15 UTC, Lo-lo78 commented
Here is an example:


Cycle Action; Increase and decrease the left border and of an item, 
increase and decrease the right border of an item

https://drive.google.com/uc?id=1zPCmGV3AODmESrIxQ39IM1Mvtgp25_Eb&export=download

Cycle Action; Time selection; works on the edges of a selection without 
feedback in play

https://drive.google.com/uc?id=16VvG3AtTFkz4wBci_tGpxuAUASN90j5d&export=download


Greetings!

2021-11-15 16:19 UTC, Lo-lo78 commented
I find it very clean and efficient; a user who does not know Reaper well 
cannot go wrong!

2021-11-15 22:24 UTC, jcsteh requested changes
This is perfect. Thank you. It needs to be documented in the readme, though. Perhaps you could add a tiny sub-section at the end of the "Usage" section (after Miscellaneous Actions) which explains how this is used. That sub-section could be called "Muting OSARA Messages in Custom/Cycle Actions" or something like that.

2021-11-16 11:06 UTC, jcsteh approved these changes
Great! Thanks!

2021-11-16 11:06 UTC, jcsteh commented on readme.md
> +The action "OSARA: Mute next message from OSARA" can be used in custom/cycle actions to mute OSARA feedback for the next action. It should be placed before each action to be muted.
nit: Split sentences onto separate lines.
```suggestion
The action "OSARA: Mute next message from OSARA" can be used in custom/cycle actions to mute OSARA feedback for the next action.
It should be placed before each action to be muted.
```

2021-11-16 11:08 UTC, merged