Rewrite CC movement using the binary search iterator
jcsteh/osara pull request #656
Opened 2022-01-22 12:05 UTC by leonardder

Fixes #434 

This pr uses the binary search iterator to navigate CCs. Similar to notes in chords, notes are stably sorted. Note however that sorting is unlikely to be equal to sorting in the event list, though sorting in there is unstable anyway.

Additionally, there are two seeminly unrelated changes in this pr, though I think they make sense here:

1. The CompareByPitch function for notes is moved to the MidiNote struct in order to keep consistency with MidiControlChange sorting.
2. I stumbled at the suggestion to use std::stable_sort instead of std::sort, that keeps order of adjacent vector items in their original order if they can't be sorted (e.g. when the pitch of two notes is equal). This can happen in chords when multiple midi tracks are merged into one item. I guess this is a theoretical thing that can easily be reverted. Wonder what you think @jcsteh .

@Batworx your feedback would be greatly appreciated. While this should fix your issue, it should also make cc navigation snappier in general.

2022-01-31 23:03 UTC, jcsteh requested changes
Thanks! Wow. Reviewing this really hurt my head. It's not your code - I can't think of a way to do it better - but I just struggled to follow it for some reason.

2022-01-31 23:03 UTC, jcsteh commented on src/midiEditorCommands.cpp
> +pair<double, int> currentCCAtPos = {-1, -1};
I'm not quite sure about the name currentCCAtPos. On one hand, I understand this now includes a position. On the other hand, it feels like currentCC is still a better name. It's not the current CC at a particular position; it's the current CC for the user, including both its position and index at that position. I think I'd prefer either currentCC (which would require renaming some local variables below) or currentCCAndPos.

2022-02-01 06:53 UTC, leonardder commented
I'm sorry for making it so difficult to grasp. I addressed your comments and added some additional comments in the process in the hope to make it more understandable now.

2022-02-02 00:14 UTC, jcsteh approved these changes
Nice commenting. That's super helpful.

2022-02-02 00:17 UTC, merged